spring:
  main:
    allow-bean-definition-overriding: true
#  thymeleaf:
#    cache: false
#    prefix: classpath:/templates/
#    suffix: .html
#    encoding: UTF-8
#    mode: HTML
  datasource:
    url: jdbc:postgresql://localhost:5432/webwithnft?useSSL=false
    username: dev
    password: devdev
    driver-class-name: org.postgresql.Driver
  profiles:
    active: dev, fast
  jpa:
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
server:
  port: 8002
mybatis:
  # typeAliasesPackage: com.xxx.xxx.dao.entity
  mapper-locations: classpath:mapper/*.xml