FROM openjdk:8
VOLUME /tmp
COPY ./target/classes/com/will/springcloud/api/entity/Dept.class /app/
COPY ./target/classes/com/will/springcloud/api/register/entity/Register.class /app/
#ENTRYPOINT ["java","-cp","app:app/lib/*","com.will.springcloud.api"]
